name: Run Python Daily

on:
  schedule:
    - cron: "0 0 * * *"  # tiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        run: python test.py
